spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Rlatldms!2!3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
