name: Backend CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  unit-test:
    name: Unit Test
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Grant Gradle permission
        run: chmod +x ./gradlew
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts', 'build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Tests
        run: ./gradlew test

  integration-test:
    name: Integration Test
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Rlatldms!2!3
          MYSQL_DATABASE: leafresh
          MYSQL_ALLOW_EMPTY_PASSWORD: false
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/leafresh
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Rlatldms!2!3
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: true
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21 for Runtime
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Build Spring Boot App
        run: ./gradlew bootJar

      - name: Start Spring Boot App
        run: |
          nohup java -Dspring.profiles.active=test -jar build/libs/*.jar > app.log 2>&1 &
          echo "Waiting for Spring Boot to be healthy..."
          for i in {1..60}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 || echo "000")
            if [ "$status" = "200" ] || [ "$status" = "401" ]; then
              echo "✅ App is ready (HTTP $status)"
              exit 0
            fi
            echo "⏳ ($i/60) status=$status"
            sleep 1
          done
          echo "❌ App did not start in time"
          echo "--- app.log ---"
          cat app.log
          exit 1

      - name: Integration Test
        run: |
          curl -v http://localhost:8080/api/challenges/group/categories || (
            echo "❌ API call failed"; 
            cat app.log;
            exit 1
          )

      - name: Stop Spring Boot App
        run: pkill -f 'java -jar'

  build-dev:
    name: Build and Push Backend Docker (develop only)
    needs: unit-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21 (Oracle)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          java-package: jdk
          oracle-license: accept
      - name: Build JAR with Gradle
        run: ./gradlew build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jchanho99/backend-dev:latest
          cache-from: type=gha,scope=build-backend-dev
          cache-to: type=gha,mode=max,scope=build-backend-dev

  build-prod:
    name: Build and Push Backend Docker (main only)
    needs: integration-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jchanho99/backend-prod:latest
          cache-from: type=gha,scope=build-backend-prod
          cache-to: type=gha,mode=max,scope=build-backend-prod
